### ISSUE TITLE
Add more python packages to miniconda env

### ISSUE THREAD

**Issue by lizziel** [JiaweiZhuang/cloud_GC#12]
The existing geo env is not sufficient to work with the gcpy package (https://bitbucket.org/gcst/gcpy) and available packages for GEOS-Chem data regridding, both lat/lon and cubed sphere. However, I am able to successfully use gcpy and regrid using xESMF with the following environment installed (see below). 

The package list is based on the one from gcpy but with additional packages added, particularly for handling cubed sphere data. Overall it includes more than is needed but provides very good coverage for what users might want. Storing the yml file within the AMI would allow users to be able to create their own environments very easily. I have a README available that I put together last year concisely giving directions for how to do this if you would like to adapt it.

Note that I cloned the gcpy, xESMF, and cubedsphere packages and then manually installed them on top of my environment, e.g. pip install -e /home/ubuntu/src/xESMF. I also had to specify an older version of xarray since gcpy is not compatible with the latest xarray version (!)

file: gcpy.yml
```yaml
name: gcpy
channels:
    - defaults
    - conda-forge
    - nesii/label/dev-esmf
dependencies:
    - python=3.6    # Python version 3.6
    - basemap       # Precursor to cartopy
    - bottleneck    # C-optimized array functions for NumPy
    - cartopy       # Geographic plotting toolkit
    - cython        # Transpile Python->C
    - dask          # Parallel processing library
    - esmpy         # ESMF python package
    - graphviz      # visualize dask graph (binary)
    - future        # Python 2/3 compatibility
    - h5py          # Wrapper for HDF5
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - notebook      # Notebook interface
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - pyresample    # Geographic resampling tools
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Macine learning library
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - six           # Python 2/3 compatibility
    - tqdm          # Nice progressbar for longer computations
    - xarray=0.9.6  # N-d labeled array library
    - xbpch         # Interface for bpch output files
    - sphinx        # documentation
    - pip:
        - codecov   # coverage tool
        - xbpch     # Interface for bpch output files
        - h5pyd     # HDF5 for Amazon S3
        - h5netcdf  # allow HDF5-backend for xarray
        - graphviz  # visualize dask graph (python package)
        - pycodestyle # tool to check style conventions (formerly pep8)
        - pytest-cov  # coverage tool
```
